[package]
name = "lunaria"
version = "0.1.0"
edition = "2024"

[dependencies]
base58 = "0.2.0"
bincode = "2.0.1"
hex = "0.4.3"
pqcrypto = { version = "0.18.1", features = ["serialization"] }
rayon = "1.10.0"
sha3 = "0.10.8"
thiserror = "2.0.12"
typenum = "1.18.0"
